---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check if filebeat is installed.
  command: "which filebeat"
  register: filebeat_installed
  changed_when: false
  failed_when: false

- name: Install Filebeat on Debian
  become: true
  apt:
    name: "{{ filebeat_package }}"
    state: present
  when: ansible_os_family == 'Debian' and filebeat_installed.rc != 0

- name: Install Filebeat on RedHat
  become: true
  yum:
    name: "{{ filebeat_package }}"
    state: present
  when: ansible_os_family == 'RedHat' and filebeat_installed.rc != 0

- include_tasks: config.yml
  when: filebeat_create_config | bool

- name: Ensure Filebeat is started and enabled at boot
  service:
    name: filebeat
    state: started
    enabled: true

- name: Restart filebeat when configuration file changes
  become: true
  service:
    name: filebeat
    state: restarted